/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:104d44da-1d6d-4037-a179-1bdfe9802f12",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_hF5wAYhRt",
    "aws_user_pools_web_client_id": "22m01hsg55l5i0ppvtsd38b7aa",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tcgrry4jrvajzcrza7t2s2foy4.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "post-image-bucket111738-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
